apiVersion: v1
kind: Service
metadata:
  name: database-service
  labels:
    name: db-service
    app: bc58-app
  namespace: bc58
spec:
  type: LoadBalancer
  ports:
    - port: 3306
      targetPort: 3306
  selector:
      name: db
  
    