apiVersion: v1
kind: Secret
metadata:
  name: mysecret
  namespace: bc58
data:
  SPRING_DATASOURCE_USERNAME: cm9vdA==
  SPRING_DATASOURCE_PASSWORD: Ym9vdGNhbXBAITU4
stringData:
  SPRING_DATASOURCE_URL: jdbc:mysql://ad84f05f932dd43258f50ff13e2ea493-1486960513.us-east-2.elb.amazonaws.com:3306/zemoso_diagnostics_bc58
